# We must duplicate the include done by $(RIOTBASE)/Makefile.include
# to also include the main board header
INCLUDES += $(addprefix -I,$(wildcard $(RIOTBOARD)/samr21-xpro/include))

include $(RIOTBOARD)/samr21-xpro/Makefile.include
