# We must duplicate the include done by $(RIOTBASE)/Makefile.include
# to also include the main board header
INCLUDES += $(addprefix -I,$(wildcard $(RIOTBOARD)/nucleo-l433rc/include))

include $(RIOTBOARD)/nucleo-l433rc/Makefile.include
