# This must be a different name than 'board' as it is implemented by 'native'
USEMODULE += board_external_nucleo-l433rc

ifneq (,$(filter netdev_default,$(USEMODULE)))
  USEMODULE += mrf24j40
endif

include $(RIOTBOARD)/nucleo-l433rc/Makefile.dep
