# This must be a different name than 'board' as it is implemented by 'native'
USEMODULE += board_external_nucleo-f446re

ifneq (,$(filter netdev_default,$(USEMODULE)))
  USEMODULE += llcc68
endif

include $(RIOTBOARD)/nucleo-f446re/Makefile.dep
