# We must duplicate the include done by $(RIOTBASE)/Makefile.include
# to also include the main board header
INCLUDES += $(addprefix -I,$(wildcard $(RIOTBOARD)/nucleo-l452re/include))

include $(RIOTBOARD)/nucleo-l452re/Makefile.include
