# We must duplicate the include done by $(RIOTBASE)/Makefile.include
# to also include the main board header
INCLUDES += $(addprefix -I,$(wildcard $(RIOTBOARD)/arduino-zero/include))

include $(RIOTBOARD)/arduino-zero/Makefile.include
